In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from tensorflow.keras.layers import Embedding
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Bidirectional
from tensorflow.keras.layers import Dropout
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Bidirectional
from tensorflow.keras.layers import Dropout


In [5]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [6]:
data=pd.read_excel('/content/drive/MyDrive/NLP/Scored data_abridged_25 March.xlsx')

In [7]:
data.head()
print(data.shape)

(149, 8)


In [8]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 149 entries, 0 to 148
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Owner Group  149 non-null    object 
 1   Notes        149 non-null    object 
 2   s1_etr       148 non-null    float64
 3   s1_etr_time  147 non-null    object 
 4   s1_svc_rstr  149 non-null    int64  
 5   s1_no_prob   149 non-null    int64  
 6   s1_hold      143 non-null    float64
 7   s1_cd        148 non-null    float64
dtypes: float64(3), int64(2), object(3)
memory usage: 9.4+ KB


In [9]:
data.isnull().sum()

Owner Group    0
Notes          0
s1_etr         1
s1_etr_time    2
s1_svc_rstr    0
s1_no_prob     0
s1_hold        6
s1_cd          1
dtype: int64

In [10]:
# Droping the nan values
data['s1_etr_time'].unique()

array([0, '90 mins', 'hour', '24 hours', '4 hours', '2 hours', '4 hrs',
       '3:30 Hrs', '60 mins', '24hours', '3 hours', '90 minutes',
       '90 Mins', '2 hrs', '8 hours', nan, '24 hrs', '6 hrs', '6 hours'],
      dtype=object)

In [11]:
data.dropna(inplace=True)
data.isnull().sum()

Owner Group    0
Notes          0
s1_etr         0
s1_etr_time    0
s1_svc_rstr    0
s1_no_prob     0
s1_hold        0
s1_cd          0
dtype: int64

In [12]:
data['s1_etr_time'].value_counts()

0             115
90 mins         5
4 hours         3
2 hrs           3
2 hours         2
24 hours        2
60 mins         2
24hours         1
3:30 Hrs        1
4 hrs           1
3 hours         1
8 hours         1
hour            1
24 hrs          1
6 hours         1
90 minutes      1
90 Mins         1
6 hrs           1
Name: s1_etr_time, dtype: int64

In [13]:
data['s1_etr_time']=np.where(data["s1_etr_time"]=='90 mins','1.5 hours',data['s1_etr_time'])
data['s1_etr_time']=np.where(data["s1_etr_time"]=='90 Mins','1.5 hours',data['s1_etr_time'])
data['s1_etr_time']=np.where(data["s1_etr_time"]=='90 minutes','1.5 hours',data['s1_etr_time'])
data['s1_etr_time']=np.where(data["s1_etr_time"]=='2 hrs','2 hours',data['s1_etr_time'])
data['s1_etr_time']=np.where(data["s1_etr_time"]=='hour','1 hour',data['s1_etr_time'])
data['s1_etr_time']=np.where(data["s1_etr_time"]=='60 mins','1 hour',data['s1_etr_time'])
data['s1_etr_time']=np.where(data["s1_etr_time"]=='4 hrs','4 hours',data['s1_etr_time'])
data['s1_etr_time']=np.where(data["s1_etr_time"]=='24 hrs','24 hours',data['s1_etr_time'])
data['s1_etr_time']=np.where(data["s1_etr_time"]=='24hours','24 hours',data['s1_etr_time'])
data['s1_etr_time']=np.where(data["s1_etr_time"]== 0,'0 hour',data['s1_etr_time'])
data['s1_etr_time']=np.where(data["s1_etr_time"]=='6 hrs','6 hours',data['s1_etr_time'])
data['s1_etr_time']=np.where(data["s1_etr_time"]=='3:30 Hrs','3.5 hours',data['s1_etr_time'])


In [14]:
data['s1_etr_time'].value_counts()

0 hour       115
1.5 hours      7
2 hours        5
24 hours       4
4 hours        4
1 hour         3
6 hours        2
8 hours        1
3.5 hours      1
3 hours        1
Name: s1_etr_time, dtype: int64

In [15]:
label_name=data['s1_etr_time'].value_counts()

In [16]:
data['s1_etr_time'].nunique()

10

In [17]:
data['s1_etr_time']=np.where(data["s1_etr_time"]=='24 hours',1,data['s1_etr_time'])
data['s1_etr_time']=np.where(data["s1_etr_time"]=='8 hours',2,data['s1_etr_time'])
data['s1_etr_time']=np.where(data["s1_etr_time"]=='6 hours',3,data['s1_etr_time'])
data['s1_etr_time']=np.where(data["s1_etr_time"]=='4 hours',4,data['s1_etr_time'])
data['s1_etr_time']=np.where(data["s1_etr_time"]=='3.5 hours',5,data['s1_etr_time'])
data['s1_etr_time']=np.where(data["s1_etr_time"]=='3 hours',6,data['s1_etr_time'])
data['s1_etr_time']=np.where(data["s1_etr_time"]=='2 hours',7,data['s1_etr_time'])
data['s1_etr_time']=np.where(data["s1_etr_time"]=='1.5 hours',8,data['s1_etr_time'])
data['s1_etr_time']=np.where(data["s1_etr_time"]=='1 hour',9,data['s1_etr_time'])
data['s1_etr_time']=np.where(data["s1_etr_time"]=='0 hour',10,data['s1_etr_time'])


In [18]:
data['s1_etr_time'].value_counts()

10    115
8       7
7       5
4       4
1       4
9       3
3       2
6       1
5       1
2       1
Name: s1_etr_time, dtype: int64

In [19]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 143 entries, 0 to 148
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Owner Group  143 non-null    object 
 1   Notes        143 non-null    object 
 2   s1_etr       143 non-null    float64
 3   s1_etr_time  143 non-null    object 
 4   s1_svc_rstr  143 non-null    int64  
 5   s1_no_prob   143 non-null    int64  
 6   s1_hold      143 non-null    float64
 7   s1_cd        143 non-null    float64
dtypes: float64(3), int64(2), object(3)
memory usage: 10.1+ KB


In [20]:
data.head()
print(data.shape)

(143, 8)


In [21]:
data['s1_etr_time'] = data['s1_etr_time'].astype('int64')

In [22]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 143 entries, 0 to 148
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Owner Group  143 non-null    object 
 1   Notes        143 non-null    object 
 2   s1_etr       143 non-null    float64
 3   s1_etr_time  143 non-null    int64  
 4   s1_svc_rstr  143 non-null    int64  
 5   s1_no_prob   143 non-null    int64  
 6   s1_hold      143 non-null    float64
 7   s1_cd        143 non-null    float64
dtypes: float64(3), int64(3), object(2)
memory usage: 10.1+ KB


In [23]:
for row in data.iterrows():
  print(row[1]['Notes'])
  print("#$"*20)


Dear Customer,

Please confirm the current latency and optimal latency to be observed on circuit.
#$#$#$#$#$#$#$#$#$#$#$#$#$#$#$#$#$#$#$#$
Dear Customer,

Please check and confirm; between which sites you are observing packet drops and what is the current latency.
#$#$#$#$#$#$#$#$#$#$#$#$#$#$#$#$#$#$#$#$
Dear Customer, 

Please check and confirm; between which sites you are observing packet drops and what is the current latency.
#$#$#$#$#$#$#$#$#$#$#$#$#$#$#$#$#$#$#$#$
Dear Customer, 

Please check and confirm; between which sites you are observing packet drops and what is the current latency.

Also provide relevant logs.
#$#$#$#$#$#$#$#$#$#$#$#$#$#$#$#$#$#$#$#$
Dear Harish,

As discussed over call, we are not receiving MAC from the customer end device.

The possible cause for the alarms could be any one of the following reasons: Loose connection, faulty ethernet connector, or faulty cable between the MUX port to your network device.

Request you to Jack Out-Jack In the cable at XYZ MU

In [24]:
data.isnull().sum()

Owner Group    0
Notes          0
s1_etr         0
s1_etr_time    0
s1_svc_rstr    0
s1_no_prob     0
s1_hold        0
s1_cd          0
dtype: int64

In [25]:
data.dropna(inplace=True)

In [26]:
data.isnull().sum()

Owner Group    0
Notes          0
s1_etr         0
s1_etr_time    0
s1_svc_rstr    0
s1_no_prob     0
s1_hold        0
s1_cd          0
dtype: int64

In [27]:
data.shape

(143, 8)

In [28]:
import re
def process_text(Notes):
    return " ".join(re.sub("(@[A-Za-z0-9]+)|([^0-9A-Za-z \t])", " ",Notes.lower()).split())

In [29]:
data['text']=data['Notes'].apply(process_text)

In [30]:
data.head()

Owner Group  ...                                               text
0  Global Premium Desk  ...  dear customer please confirm the current laten...
1  Global Premium Desk  ...  dear customer please check and confirm between...
2  Global Premium Desk  ...  dear customer please check and confirm between...
3  Global Premium Desk  ...  dear customer please check and confirm between...
4          Premium SOC  ...  dear harish as discussed over call we are not ...

[5 rows x 9 columns]

In [31]:
data['s1_etr_time'].unique()

array([10,  8,  9,  1,  4,  7,  5,  6,  2,  3])

In [32]:
data=data[['text','s1_etr_time']]

In [33]:
data.head()

text  s1_etr_time
0  dear customer please confirm the current laten...           10
1  dear customer please check and confirm between...           10
2  dear customer please check and confirm between...           10
3  dear customer please check and confirm between...           10
4  dear harish as discussed over call we are not ...           10

In [34]:

from tensorflow.keras.preprocessing.text import one_hot
voc_size=5000
onehot_repre=[one_hot(words,voc_size)for words in data['text']]

In [35]:
onehot_repre

[[4746,
  2268,
  1459,
  2753,
  4731,
  4653,
  1447,
  1797,
  63,
  1447,
  2248,
  2216,
  4617,
  2287,
  807],
 [4746,
  2268,
  1459,
  937,
  1797,
  2753,
  313,
  3274,
  4198,
  4148,
  2626,
  3669,
  4419,
  784,
  1797,
  4083,
  611,
  4731,
  4653,
  1447],
 [4746,
  2268,
  1459,
  937,
  1797,
  2753,
  313,
  3274,
  4198,
  4148,
  2626,
  3669,
  4419,
  784,
  1797,
  4083,
  611,
  4731,
  4653,
  1447],
 [4746,
  2268,
  1459,
  937,
  1797,
  2753,
  313,
  3274,
  4198,
  4148,
  2626,
  3669,
  4419,
  784,
  1797,
  4083,
  611,
  4731,
  4653,
  1447,
  1907,
  4850,
  3080,
  2990],
 [4746,
  1262,
  1700,
  2471,
  3191,
  429,
  264,
  2626,
  3451,
  3490,
  3249,
  2416,
  4731,
  2268,
  4223,
  1041,
  4731,
  3561,
  1672,
  981,
  4731,
  4218,
  3262,
  2216,
  3528,
  2526,
  90,
  4731,
  2036,
  4466,
  4885,
  4021,
  2075,
  3016,
  13,
  2360,
  2075,
  637,
  313,
  4731,
  46,
  3374,
  2248,
  2259,
  481,
  1041,
  2751,
  4148,
  2248,

In [36]:

sent_length=20
embedding_docs=pad_sequences(onehot_repre,padding='pre',maxlen=sent_length)

In [37]:
x=np.array(embedding_docs)
x

array([[   0,    0,    0, ..., 4617, 2287,  807],
       [4746, 2268, 1459, ..., 4731, 4653, 1447],
       [4746, 2268, 1459, ..., 4731, 4653, 1447],
       ...,
       [ 377, 2769,  295, ...,  222,  770, 3579],
       [1172, 2124, 3991, ..., 3091, 2071, 3130],
       [2248, 4890, 3990, ..., 2526, 1831, 3187]], dtype=int32)

In [38]:
y=data['s1_etr_time']
y

0      10
1      10
2      10
3      10
4      10
       ..
144    10
145    10
146    10
147     3
148     4
Name: s1_etr_time, Length: 143, dtype: int64

In [39]:
sent_length=20
voc_size=5000
embedding_vector_features=40
model1=Sequential()
model1.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model1.add(Bidirectional(LSTM(100)))
model1.add(Dropout(0.2))
model1.add(Dense(4,activation='relu'))
model1.add(Dense(11,activation='softmax'))
model1.compile(loss='sparse_categorical_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model1.summary())

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 20, 40)            200000    
_________________________________________________________________
bidirectional (Bidirectional (None, 200)               112800    
_________________________________________________________________
dropout (Dropout)            (None, 200)               0         
_________________________________________________________________
dense (Dense)                (None, 4)                 804       
_________________________________________________________________
dense_1 (Dense)              (None, 11)                55        
Total params: 313,659
Trainable params: 313,659
Non-trainable params: 0
_________________________________________________________________
None


In [40]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.22,random_state=120,)

In [41]:
x_train.shape,y_train.shape

((111, 20), (111,))

In [42]:
x_test.shape,y_test.shape

((32, 20), (32,))

In [43]:

from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.metrics import accuracy_score,f1_score, recall_score
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier

In [44]:
model1.fit(x_train,y_train,validation_data=(x_test,y_test),epochs=150,batch_size=10)

Epoch 1/150
12/12 [==============================] - 33s 102ms/step - loss: 2.3228 - accuracy: 0.7174 - val_loss: 1.7980 - val_accuracy: 0.8125
Epoch 2/150
12/12 [==============================] - 0s 21ms/step - loss: 1.4257 - accuracy: 0.8362 - val_loss: 1.2269 - val_accuracy: 0.8125
Epoch 3/150
12/12 [==============================] - 0s 21ms/step - loss: 1.0176 - accuracy: 0.7891 - val_loss: 1.2190 - val_accuracy: 0.8125
Epoch 4/150
12/12 [==============================] - 0s 20ms/step - loss: 0.8835 - accuracy: 0.7680 - val_loss: 1.1030 - val_accuracy: 0.8125
Epoch 5/150
12/12 [==============================] - 0s 20ms/step - loss: 0.5450 - accuracy: 0.8410 - val_loss: 1.0356 - val_accuracy: 0.8125
Epoch 6/150
12/12 [==============================] - 0s 21ms/step - loss: 0.5585 - accuracy: 0.8357 - val_loss: 1.3020 - val_accuracy: 0.8125
Epoch 7/150
12/12 [==============================] - 0s 20ms/step - loss: 0.6708 - accuracy: 0.8153 - val_loss: 0.9471 - val_accuracy: 0.8125
Epoc

In [45]:

y_predict_test=model1.predict_classes(x_test)
y_predict_test

/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


array([10, 10, 10,  8, 10, 10, 10, 10,  1, 10, 10, 10, 10,  7,  8,  3, 10,
       10, 10, 10, 10,  6, 10,  3, 10, 10, 10, 10, 10, 10, 10, 10])

In [46]:
y_predict_train=model1.predict_classes(x_train)
y_predict_train

/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


array([10,  1,  1, 10, 10, 10, 10,  7,  8, 10, 10, 10, 10, 10, 10, 10, 10,
       10,  4, 10, 10, 10, 10, 10, 10, 10,  3, 10, 10, 10, 10, 10, 10,  1,
        7,  3,  8, 10, 10, 10, 10, 10, 10, 10, 10,  1, 10,  1, 10, 10, 10,
       10, 10,  3, 10, 10,  1, 10,  6,  3, 10, 10, 10, 10, 10, 10, 10,  4,
       10, 10, 10, 10, 10,  4, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
       10, 10, 10, 10, 10, 10,  7, 10, 10, 10, 10,  8,  3, 10, 10, 10, 10,
       10,  8, 10, 10, 10, 10, 10,  7, 10])

In [47]:
from sklearn.metrics import confusion_matrix
confusion_metrix=confusion_matrix(y_test,y_predict_test)
confusion_metrix

array([[ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  1],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  1,  2,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  2],
       [ 1,  2,  0,  1,  0,  0,  0, 22]])

In [48]:
from sklearn.metrics import classification_report,plot_confusion_matrix
print(classification_report(y_test,y_predict_test))

              precision    recall  f1-score   support

           1       0.00      0.00      0.00         0
           3       0.00      0.00      0.00         0
           4       0.00      0.00      0.00         1
           6       0.00      0.00      0.00         0
           7       0.00      0.00      0.00         0
           8       1.00      0.67      0.80         3
           9       0.00      0.00      0.00         2
          10       0.88      0.85      0.86        26

    accuracy                           0.75        32
   macro avg       0.23      0.19      0.21        32
weighted avg       0.81      0.75      0.78        32



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
